### ISSUE TITLE
Add dry run

### ISSUE THREAD

**Issue by thinkl33t** [pwaring/dns-sync-zone#11]
It would be useful in our CI to be able to dry run the script, performing initial validation and outputting the list of commands to be sent, with a return code sent depending on validity.

**Comment by pwaring** [comment]
Agreed, this almost happens already in that the script will output the list of commands to be added/removed. It shouldn't be too much work to refactor the code so that there's a dry run option. I'll have a look at this one tonight.

**Comment by pwaring** [comment]
Does #14 solve this issue for you? It adds a `--dry-run` option but I'm not sure about the return codes.
