### ISSUE TITLE
When --diffs is used, CAA records are still deleted / added

### ISSUE THREAD

**Issue by thinkl33t** [pwaring/dns-sync-zone#37]
DELETE @ 3600 CAA 0 issue letsencrypt.org
DELETE @ 3600 CAA 0 iodef mailto:operations@codethink.co.uk
ADD @ 3600 CAA 0 issue "letsencrypt.org"
ADD @ 3600 CAA 0 iodef "mailto:operations@codethink.co.uk"
DELETE @ 3600 CAA 0 issue letsencrypt.org
DELETE @ 3600 CAA 0 iodef mailto:operations@codethink.co.uk
ADD @ 3600 CAA 0 issue "letsencrypt.org"
ADD @ 3600 CAA 0 iodef "mailto:operations@codethink.co.uk"

**Comment by thinkl33t** [comment]
Looks like an issue with the quoting?

**Comment by pwaring** [comment]
Just tried this with my test domain and got the same result. I agree it does look like a quoting issue, I think it's the same as #19 whereby Mythic Beasts are stripping double quotes from input, saving the stripped version to their database, and then there are two ways the data is given back to the user:

 1. Via the API LIST command: As saved, without double quotes.
 2. Via DNS (e.g. `dig +short caa example.org`): Double quotes are added before the data is served up.

I'm not sure why they do things this way, as double quoting seems to be the correct way for the record data to be saved and stored. I'll drop them an email tomorrow and see if I can get to the bottom of this.

**Comment by thinkl33t** [comment]
Aye, removing the quoting from the file seemed to fix it.

**Comment by pwaring** [comment]
I've sent an email to Mythic, just waiting for their response.

**Comment by pwaring** [comment]
Apparently the API is a bit broken in the way it handles quotes, although technically both of these are equivalent since you only need to quote records if they contain spaces:

```
@ 300 CAA 0 issue letsencrypt.org 
@ 300 CAA 0 issue "letsencrypt.org"
```

So the solution for now is to remove the quotes, unless there's a space in the string (please let me know if you have a CAA example which does and I'll test that).

**Comment by pwaring** [comment]
Linking this to #39, which seems to suggest that the quoting behaviour has changed again.

**Comment by pwaring** [comment]
I think this is fixed now, if you quote the CAA records in your zone file they should work and the behaviour with `--diffs` should be correct. Please let me know if it's not and I'll re-open the issue.
