### ISSUE TITLE
Allow hostnames to start with a number

### ISSUE THREAD

**Issue by pwaring** [pwaring/dns-sync-zone#48]
Currently the following records fail validation:

```
111 300 A 127.0.0.1
111 300 AAAA ::1
```

However, 111 is a valid hostname, e.g. 111.nhs.uk. The above records should be permitted, and we also need unit tests that will fail if the records above do not validate.

**Comment by pwaring** [comment]
Changing this seems to break a few tests which assume that labels such as `192.168.1.1` are invalid (but allowing that as a label breaks MX records as what looks like an IP address cannot be the target of an MX).

**Comment by thinkl33t** [comment]
Any thoughts on a fix for this?  Its causing us grief with various randomly generated prove-you-own-this-domain type stuff.

**Comment by pwaring** [comment]
> Any thoughts on a fix for this? Its causing us grief with various randomly generated prove-you-own-this-domain type stuff.

Haven't had any spare time to look at it unfortunately. I'll take a look at the PR this week though to see if that solves the issue.

**Comment by thinkl33t** [comment]
After doing some research (as i was still having trouble, see #52), i found https://datatracker.ietf.org/doc/html/rfc1123 states that host software MUST allow domains to start with a digit.  This appears to be a divergence between the hostname rfc and the dns rfc, and the former is widely used enough to form the defacto standard.

I suggest we remove the not-a-digit checker entirely, or gate it behind the `--strict` flag
