### ISSUE TITLE
Other record types

### ISSUE THREAD

**Issue by thinkl33t** [pwaring/dns-sync-zone#9]
It would be useful to have support for CAA, SSHFP and ANAME records

I know ANAME arent *technically* a real type, but mythic beasts support them, and we make use of them.

**Comment by pwaring** [comment]
ANAME *should* work already, in that it will pass basic validation (it's listed in `valid_types_basic`). I haven't tested it though.

I can't see any problems with adding CAA and SSHFP - the basic validation for SSHFP should be the same as TXT and for CAA it will probably be similar to MX. There's also issue #3 for validating the contents of the record, as opposed to just the structure.
